# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Deploy ParSNP image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./parsnp/1.5.6"
      dockerfile_name: "Dockerfile"
      cache: "parsnp"

  build-to-deploy:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      path_to_context: "./parsnp/1.5.6"
      dockerfile_name: "Dockerfile"
      cache: "parsnp"
      container_name: "parsnp"
      tag: 1.5.6

  run-singularity:
    needs: build-to-deploy  # test singularity run on newly pushed Docker image
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "parsnp:1.5.6"
