# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.

name: Deploy Pangolin 3.1.20-pangolearn-2022-02-28-slim image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./pangolin/3.1.20-slim/"
      dockerfile_name: "Dockerfile"
      cache: "pangolin"

  build-to-deploy:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      path_to_context: "./pangolin/3.1.20-slim/"
      dockerfile_name: "Dockerfile"
      cache: "pangolin"
      container_name: "pangolin"
      tag: |
        3.1.20-pangolearn-2022-02-28-slim
        latest

  run-singularity:
    needs: build-to-deploy  # test singularity run on newly pushed Docker image
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "pangolin:3.1.20-pangolearn-2022-02-28-slim"
