
name: Deploy Trimmomatic image

on: workflow_dispatch

jobs:

  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./trimmomatic/0.39"
      dockerfile_name: "Dockerfile"
      cache: "trimmomatic"

  build-to-deploy:
    needs: build-to-test
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      quay_username: ${{ secrets.quay_username }}
      quay_robot_token: ${{ secrets.quay_robot_token }}
    with:
      path_to_context: "./trimmomatic/0.39"
      dockerfile_name: "Dockerfile"
      cache: "trimmomatic"
      container_name: "trimmomatic"
      tag: "0.39"

  run-singularity:
    needs: build-to-deploy
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "trimmomatic:0.39"
