name: Test htslib image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'htslib/*/Dockerfile'

jobs:
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "htslib/1.15"
      dockerfile_name: "Dockerfile"
      cache: "htslib"
