name: Test ParSNP image

on:
  pull_request:
    paths:
      - "./parsnp/1.5.6/*"

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./parsnp/1.5.6"
      dockerfile_name: "Dockerfile"
      cache: "parsnp"
