name: Test htslib image

env:
  tool: "htslib"
  version: "1.15"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'htslib/1.15/Dockerfile'

jobs:
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "htslib/1.15"
      cache: "htslib"
